include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup(TARGETS)
add_library(cpp-peglib ALIAS CONAN_PKG::cpp-peglib)
add_library(spdlog ALIAS CONAN_PKG::spdlog)
add_library(cxxopts ALIAS CONAN_PKG::cxxopts)
add_library(termcolor ALIAS CONAN_PKG::termcolor)
add_library(tl-expected ALIAS CONAN_PKG::tl-expected)
add_library(gtest ALIAS CONAN_PKG::gtest)
add_library(gtest_main INTERFACE)
add_library(fmt ALIAS CONAN_PKG::fmt)
